version: 2.0.{build}
image: Visual Studio 2017
configuration: Release

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
  
before_build:
  - nuget restore StateMachine.sln

build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: normal
  
nuget:
  disable_publish_on_pr: true
  
deploy:
  - provider: NuGet
    api_key:
      secure: 8D5BgFGJjxoU+cBObT7wy9v/gQC2koECcVyeg9Z6H0mtH9vIa/+HFhXx1MuV9N5t
    on:
      appveyor_repo_tag: true